### ISSUE TITLE
cChocoPackageInstaller not finding package in local source

### ISSUE THREAD

**Issue by MubSalim** [PowerShellOrg/cChoco#119]
Hi,

I've been playing around with cChoco and was attempting to install SQL 2016. I have set up a chocolatey repo on a remote server and I'm able to set it as a source using the cChocoSource resource. I can then see it when I do a "Choco sources" and I can even install SQL using the sql2016 package I created if I run “choco install sql2016”

The issue is if I try an install of the same package using cChocoPackageInstaller I get an error saying 

2019-03-01 14:48:20,878 2584 [ERROR] - sql2016 not installed. The package was not found with the source(s) listed.
 Source(s): '\\remoteservername\c$\ChocolateyRepo\;https://chocolatey.org/api/v2/'

The configuration I’m using is as follows:

```
Configuration ToolInstall
{
    Import-DscResource -ModuleName cChoco

    Node $AllNodes.NodeName
    {
        cChocoInstaller installChoco {
            InstallDir = "C:\Program Files\Chocolatey"
        }

        cChocoSource SetSource {
            Name     = "LCCRepo"
            source   = "\\remoteservername\c$\ChocolateyRepo\"
            Priority = 1
            
        }
        
        foreach ($tool in $ConfigurationData.ToolData.Tools) {
            cChocoPackageInstaller $tool {
                Name   = $tool
                Ensure = "Present"
            }
        }
    }
}
```

I’m new to chocolatey so any assistance would be appreciated. 

Thanks

**Comment by pauby** [comment]
Does the account DSC is running under have access to that share?

**Comment by MubSalim** [comment]
The account does have admin access. This is a two server dev environment so everything is pretty open.

**Comment by pauby** [comment]
@MubSalim The error you are getting is one from choco itself so I don't think this is a cChoco issue. Can you reach out to the Gitter channels for choco (https://gitter.im/chocolatey/choco)? Let us know how you get on and we can come back to this issue.

**Comment by pauby** [comment]
]Gitter conversation](https://gitter.im/chocolatey/choco?at=5c8100a4f895944c08559fc4) for this resolved the issue which turned out to be permissions on the share. DSC, by default, runs under the SYSTEM account on the local computer. This had no permissions to the share. 

The fix in this case was to use the `PsDscRunAsCredential` which is documented at [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/dsc/configurations/runasuser).

[Interesting article](https://jermdavis.wordpress.com/2015/11/23/wait-who-is-dsc-running-as-again/) on how to check which account DSC is running under.
