### ISSUE TITLE
cChocoInstaller's choco existence check is more advanced than cChocoPackageInstall

### ISSUE THREAD

**Issue by nebffa** [PowerShellOrg/cChoco#26]
cChocoInstaller checks that choco is on the system path by doing `$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")`. cChocoPackageInstall should also do this so that it too can check whether choco was installed by other means.

**Comment by DamianBis** [comment]
cChocoPackageInstall should only care about whether chocolatey is installed or not. it shouldn't care about where it is installed or if it was installed by any specific way. Because it's perfectly legitimate usage that i want to install chocolatey manually or some other way but then use cChocoPackageInstall to install the packages.

**Comment by pauby** [comment]
I can't see the issue here - [cChocoInstaller](https://github.com/chocolatey/cChoco/blob/development/DSCResources/cChocoInstaller/cChocoInstaller.psm1#L96) and [cChocoPackageInstall](https://github.com/chocolatey/cChoco/blob/development/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L182).

I appreciate this is an old issue. Just trying to clear it up.

**Comment by pauby** [comment]
I can't see the issues with this one and there has been no updates to this in some time, so I'm going to go ahead and close it. We can always reopen it again if needed.
