### ISSUE TITLE
Chocolatey 0.9.10 and exit codes - cChoco is now reporting successful package installs as failures

### ISSUE THREAD

**Issue by ferventcoder** [PowerShellOrg/cChoco#30]
Related to #19, but better context.

I mentioned this before in April - https://github.com/chocolatey/choco/issues/512. 0.9.10 just released today and folks are going to start reporting breakages even though we noted it in our release notes and tried to give plenty of notice to folks that it was coming (2 months notice in this case).

Here is the relevant portion of the [ChangeLog](https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0910-june-17-2016) (under breaking changes):

> - Exit with the same exit code as the software being installed - see [#512](https://github.com/chocolatey/choco/issues/512)
> 
> There are more exit codes from Chocolatey now that indicate success -`0`, `1605`, `1614`, `1641`, and `3010`. You may need to adjust anything you were using that would only check for 0 and nonzero.
> If you need the previous behavior, be sure to disable the feature `usePackageExitCodes` or use the `--ignore-package-exit-codes` switch in your choco commands.

**Comment by lawrencegripper** [comment]
Morning, 

I reviewed this when it was raised, as we rely on the Test-Resource call to validate the install of the package rather than checking an exit code from the choco install command I don't believe this will affect the DSC Resource. 

Installer invoked here: https://github.com/PowerShellOrg/cChoco/blob/master/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L145

Check install run here, using choco list -lo: https://github.com/PowerShellOrg/cChoco/blob/master/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L182

May not be the ideal approach for the resource longer term but has worked well for me in the past. 

On a separate note there are a fair few oustanding issues in the repo and over recent months I've not been able to give time to it, if you know any community members who'd be interesting in assisting reviewing and updating the resource could you point them this way?

**Comment by lawrencegripper** [comment]
#31 - Made an issue to track request for assistance.
