### ISSUE TITLE
cChocoPackageInstall Allow "Latest" as a package version

### ISSUE THREAD

**Issue by DamianBis** [PowerShellOrg/cChoco#39]
From looking at the code (please correct me if i'm wrong) If you don't specify a version and a newer version is available the cChocoPackageInstall will not do anything.

cChocoPackageInstall should allow "latest" as a package version and then any time it checks if there is a newer version installed on the server than the client it should upgrade that package.

**Comment by lawrencegripper** [comment]
I'd been considering this functionality a while back but wasn't sure if it was a bit too invasive for the install resouce. I'm not sure I'd expect it to behave that way. 

Would it be better to have a separate resource, which is responsible for updating packages? Potentially (sudo code) like ... cChocoUpdate { packages: ["chrome", "notepadplusplus"] }

**Comment by ferventcoder** [comment]
@lawrencegripper @DamianBis "latest" would line it up more with something like Puppet, where you can ensure it is installed, absent, latest, or a particular version. Of course the resource name is just `package` and not `cChocoPackageInstall`. You could think of "Install" in that word as the noun "install" and not the verb/action. Especially if this is how you ensure that it is removed.

**Comment by DamianBis** [comment]
I'll get working on this some time this week, @ebekker what are your thoughts on using cChocoPackageInstall or making a new resource cChocoUpdate?

**Comment by ebekker** [comment]
I'm OK with _enhancing_ the existing resource and adjusting in a similar manner to what @ferventcoder is suggesting (i.e. add a third option of `Latest` to the `Ensure` property) or just simply using a sentinel value like `TRACK_LATEST` for the `Version` property.  This does seem very _natural_ to me from a user perspective.

@lawrencegripper to address your thoughts, I think this is still more in keeping with the spirit of DSC -- the natural/gradual migration toward a declared state -- in this case the state declaration is the same but the _surroundings_ have changed.  So I don't think it necessarily merits a whole new resource.

My concern is more on implementation details of what this would mean -- since DSC is by default running every 15 or 30 mins (depending on push or pull model), does this mean we need to reach out to the choco repo on this same cadence to compare what is installed and what is available?  And if this scales out to lots of users, all of them would be hitting up the choco repo continuously, and potentially on lots of servers per user.  That seems very inefficient to me.  A more practical approach might be to define an independent cadence of how frequently to test, say once a day or once every 3 days and maintain some state somewhere to support this.  Or do you guys not feel this is really a concern?

@ferventcoder, in the case of Puppet, how do you handle something like this?  Is it not as much of an issue because the general refresh/update cadence is not as frequent?

**Comment by ferventcoder** [comment]
> My concern is more on implementation details of what this would mean -- since DSC is by default running every 15 or 30 mins (depending on push or pull model), does this mean we need to reach out to the choco repo on this same cadence to compare what is installed and what is available? 

Similarly, Puppet also runs on a schedule of every 30 minutes by default. 

Organizations, which are typically the users of things like DSC and Puppet, do not typically use the community repository (https://chocolatey.org/packages). 

For latest, it typically means check what is most up to date through `choco outdated -r` and parsing that output.

> And if this scales out to lots of users, all of them would be hitting up the choco repo continuously, and potentially on lots of servers per user. That seems very inefficient to me. A more practical approach might be to define an independent cadence of how frequently to test, say once a day or once every 3 days and maintain some state somewhere to support this. Or do you guys not feel this is really a concern?

This would be awesome. One thing to consider is that choco will move to control this same area with package indexes. The index will control that cadence of when to reach back out to the remote repositories for updates.

While it does feel somewhat inefficient, know that we've optimized and cached searches for single package resources, so they return very quickly. So as this scales out to lots of users, it doesn't have a significant cost against the community repository.

**Comment by ferventcoder** [comment]
To give you a general idea, this was yesterday:

![image](https://cloud.githubusercontent.com/assets/63502/17410400/1a780a9c-5a39-11e6-9d9b-d68f54f87f1b.png)

![image](https://cloud.githubusercontent.com/assets/63502/17410404/273b4cd0-5a39-11e6-9dad-b957af283890.png)

**Comment by ebekker** [comment]
OK, I'm sold on my efficiency concerns.  I guess now to come to consensus on conventions for how to express this _pinning_ to the latest version of a package...

**Comment by javydekoning** [comment]
The resource now has a autoupgrade boolean available for use, hence we are now closing this issue.
