### ISSUE TITLE
Turn off download progress

### ISSUE THREAD

**Issue by ferventcoder** [PowerShellOrg/cChoco#83]
In 0.10.4, Chocolatey started to show [download progress for packages as well](https://github.com/chocolatey/choco/issues/1134) as any downloaded resources. When something else is using Chocolatey and capturing output for logging purposes, it can overwhelm the log. 

This is the case in PowerShell DSC. You receive a cryptic error similar to `The WS-Management service cannot process the request. The computed response packet size (3388031) exceeds the maximum envelope size that is allowed (512000).`

When 0.10.4+ is detected, add `--no-progress` (https://github.com/chocolatey/choco/issues/917) automatically when managing packages with cChoco.

**Comment by jrdnr** [comment]
@ferventcoder Should this be Up for grabs or are you working on it? I have working code to patch this that I'm using internally, but its a little fragile because I just pasted the same check into the install/uninstall/ and update functions.  The right way to fix this might be to refactor the install/uninstall/update functions to have more consistent code and naming across them, and actually break running `choco $params` into its own function so that anytime there is a a change to the core choco application output it only has to be updated one place.

**Comment by ferventcoder** [comment]
@jrdnr up for grabs.

**Comment by ferventcoder** [comment]
Go for the simple changes first and we can look for the more invasive changes later.

**Comment by jessejacob** [comment]
Just wanted to say thanks y'all for implementing this. HUGE reduction in Packer log sizes where I was using lots of choco operations!

**Comment by jrdnr** [comment]
@ferventcoder Any chance of getting this PR merged?

**Comment by TTimo** [comment]
I would like to see this addressed as well.

**Comment by jrdnr** [comment]
@TTimo The PR to fix was submitted almost a year ago, but I haven't been able to get a response from the maintainers.

**Comment by FinickyCode** [comment]
A possible workaround while waiting for this PR to be merged is to disable progress globally.
```
choco feature disable -n=showDownloadProgress
```

**Comment by pauby** [comment]
The PR is working it's way through. We have been very slow to pick this up. Changes have been requested and would hope to get this ready for the next release.
